apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joke-backend
  template:
    metadata:
      labels:
        app: joke-backend
    spec:
      containers:
        - name: joke-backend
          # image: joke-backend:latest
          image: bijayrajsinghdeo/joke-backend:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
