trigger:
  branches:
    include:
      - main
      - prod

pool:
  name: Default

steps:
# CI
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      cd frontend
      npm install
      npm run build
    displayName: 'Build React app'

  - script: |
      echo "Building frontend image..."
      docker build -t bijayrajsinghdeo/joke-frontend:prod ./frontend

      echo "Pushing frontend image..."
      docker push bijayrajsinghdeo/joke-frontend:prod
    displayName: 'Build and Push Docker Image'

# CD
  - script: |
      echo "Deploying frontend to Minikube..."
      kubectl config use-context minikube
      kubectl apply -f frontend/k8s/deployment.yaml
      kubectl apply -f frontend/k8s/service.yaml
      kubectl apply -f k8s/ingress.yaml
    displayName: 'Deploy frontend and ingress to Minikube'