trigger:
  branches:
    include:
      - main
      - prod

pool:
  name: Default

variables:
  imageName: 'joke-backend'

steps:
# CI
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd backend
    npm install
  displayName: 'Install dependencies'

# Docker Build and Push
- script: |
    echo "Logging into Docker Hub..."
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    echo "Building image..."
    docker build -t $DOCKER_USERNAME/joke-backend:prod .

    echo "Pushing image..."
    docker push $DOCKER_USERNAME/joke-backend:prod
  displayName: 'Build and Push Docker Image'
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

# CD
- script: |
    echo "Deploying backend to Minikube..."
    kubectl config use-context minikube
    kubectl apply -f backend/k8s/deployment.yaml
    kubectl apply -f backend/k8s/service.yaml
  displayName: 'Deploy backend to Minikube'
